config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do 
    member do
      get 'raffle'
      get 'secret_friend'
      get 'messages'
    end
    resources :participants, only: [:create, :destroy, :show]
  end

  get '/participants/:id/confirm', :to => 'participants#confirm', :as => :confirm_participant
    
  authenticated :user do
    root 'groups#index', as: "authenticated_root"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	belongs_to :user
	has_many :participants, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: { message: 'O nome deve ser preenchido' }

  def raffle
  	raise 'Este grupo já foi sorteado!' if raffled

  	partics = participants.where('user_id IS NOT NULL')

    raise 'O sorteio só pode ser realizado com três ou mais participantes confirmados!' if partics.count < 3  

    copy = partics.dup
	
    array = []
    while true do
      copy = copy.shuffle
      array = partics.zip(copy)
      
      break if array.all? do |(p, f)|
        p != f
      end
    end
    
    array.each do |(p, f)|
      p.update(sec_user: f.user)
    end
   
    # need send e-mail
      
    update(raffled: true)
  end	
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}  

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end  

  after_create_commit { MessageBroadcastJob.perform_later(self) }  
end

app/models/participant.rb
class Participant < ApplicationRecord
  before_create :confirmation_token, unless: :confirm_token?

  validates :email,
    format: {
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
      message: "Informe um e-mail válido" 
    },
    uniqueness: { scope: :group_id,
    message: "Você já adicionou este e-mail para este grupo" }

  belongs_to :group
  belongs_to :user, class_name: 'User', optional: true
  belongs_to :sec_user, class_name: 'User', optional: true
  
  def confirm_participation(user)
    self.user = user
    self.confirm_token = nil
    save!(validate: false)
  end

  private
    def confirmation_token
      self.confirm_token = SecureRandom.uuid
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups 
  has_many :messages, dependent: :destroy
  has_many :user_participants, class_name: 'Participant', foreign_key: 'user_id', dependent: :nullify
  has_many :sec_user_participants, class_name: 'Participant', foreign_key: 'sec_user_id', dependent: :nullify

  validates :username, presence: true

	def name
	  email.split('@')[0]
	end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  helper_method :groups_by_user
  
  def groups_by_user
    Group.joins(:participants).distinct.where('participants.user_id = ?', current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
     devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:edit, :update, :destroy]
  before_action :set_group_show, only: :show
  before_action :set_group_with_participants, only: :raffle

  # GET /groups
  def index
    @groups = groups_by_user
  end

  # GET /groups/1
  def show
    @participant = Participant.new
  end

  # GET /groups/new
  def new
    @group = current_user.groups.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = current_user.groups.build(group_params)
    # @group.build_chat_room
    participant = @group.participants.build(email: current_user.email)
    participant.user = @group.user
    
    if @group.save
      redirect_to @group, notice: 'Grupo criado com sucesso'
    else
      render :new
    end  
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Grupo atualizado com sucesso'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Groupo deletado com sucesso'
  end

  def raffle
    msg = 'Sorteio realizado com sucesso! ;)'
    begin
      @group.raffle;
    rescue => e
      msg = e
    end    
    redirect_to @group, notice: msg
  end

  def secret_friend
    @participant = Participant.where({group_id: params[:id], user_id: current_user}).take

    redirect_to_groups(@participant)
  end

  def messages
    @group = Group.joins(:participants).includes(:messages).where('groups.id = ? AND participants.user_id = ?', params[:id], current_user.id).take
    redirect_to_groups(@group)
    @message = Message.new
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group      
      @group = Group.where({id: params[:id], user_id: current_user}).take;

      redirect_to_groups(@group)
    end

    def set_group_show
      @group = Group.joins(:participants).distinct.where('groups.id = ? AND participants.user_id = ?', params[:id], current_user.id).take

      redirect_to_groups(@group)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :address, :city)
    end

    def set_group_with_participants
      @group = Group.includes(:participants).where({id: params[:id], user_id: current_user}).take;

      redirect_to_groups(@group)
    end

    def redirect_to_groups(obj)
      redirect_to groups_url if obj.blank?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController  
  before_action :authenticate_user!
  before_action :set_group, only: [:new, :create]
  before_action :set_participant, only: :destroy

  def show
  end

  def create
    @participant = @group.participants.build(participant_params)

    respond_to do |format|
      if @participant.save
        ParticipantMailer.participant_confirmation(@participant).deliver_later
        format.js { render action: 'show', status: :created, location => [@grupo, @participant] }
      else
        format.js { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @participant.destroy
    redirect_to group_path(params[:group_id])
  end	

  def confirm
    participant = Participant.find_by_confirm_token(params[:id])
    
    if participant && participant.email == current_user.email
      participant.confirm_participation(current_user)
      redirect_to participant.group, notice: 'Bem vindo, obrigado pela sua confirmação'
    else
      redirect_to groups_path, notice: 'Houve um problema na confirmação, Verifique se ao logar você utilizou o mesmo e-mail que foi enviado'
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:group_id])

      redirect_to groups_url if @group.blank?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:email)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end	
end

app/helpers/groups_helper.rb
module GroupsHelper
  # def all_participants(order)
  #   Participant.joins(some_class: :parent).where("some_class_id = :id OR parents_some_classes.id = :id", {id: self.id}).uniq.order(order)
  # end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/groups/_form.html.erb
<div class="row">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Informações do grupo <%= group.name %></h4></div>
      <div class="panel-body">
        <%= form_for group, html: {role:"form"} do |f| %>
          <% flash.now[:notice] = flash[:notice].to_a.concat group.errors.map { |attr, msg| msg } %>
          
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-group"></i></span>
            <%= f.text_field :name, class: "form-control", placeholder: 'Nome' %>
          </div>

          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-home"></i></span>
            <%= f.text_field :address, class: "form-control", placeholder: 'Endereço' %>
          </div>

          <div class="form-group input-group">
          <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>      
            <%= f.text_field :city, class: "form-control", placeholder: 'Cidade' %>
          </div>
          
          <%= f.submit "Salvar", class:"btn btn-primary" %>

          <%if group.id? %>    
            <%= link_to "Excluir Grupo", group_path(group), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o grupo?' }, class: "btn btn-danger"%>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/groups/_group_panel.html.erb
<div class="col-lg-4 col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-3">
          <i class="fa fa-group fa-3x"></i>
        </div>
        <div class="col-xs-9 text-right">
          <div class="huge"><%= group.name %></div>
          <div>Número de participantes: <%=group.participants.size %></div>
        </div>
      </div>
    </div>
    <%= link_to group_path(group) do %>
      <div class="panel-footer">
        <span class="pull-left">Mais sobre <%= group.name %></span>
        <span class="pull-right"><i class="fa fa-ellipsis-v"></i></span>
        <div class="clearfix"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<% content_for :title do %>
  Configurações do grupo
<% end %>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<% content_for :title do %>
  Grupos
<% end %>

<div class="row">
  <%= render partial: 'group_panel', collection: @groups, as: :group %>
</div>

app/views/groups/messages.html.erb
<% content_for :title do %>
  Mensagens do grupo <%= @group.name %>
<% end %>

<div id="messages" data-group-id="<%= @group.id %>">
  <%= render @group.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'group_id', @group.id %>
  <div class="form-group">
    <!-- <%= f.label :body %> -->
    <%= f.text_area :body, class: 'form-control', placeholder: 'Digite aqui sua mensagem'  %>
    <small class="text-muted">De 2 a 1000 caracteres</small>
  </div>

  <%= f.submit "Enviar", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/groups/new.html.erb
<% content_for :title do %>
  Novo Grupo
<% end %>

<%= render 'form', group: @group %>

app/views/groups/secret_friend.html.erb
<% content_for :title do %>
  Seu amigo é...
<% end %>
<div>
	<h3>O seu amigo secreto é <strong><%=@participant.sec_user.username%></strong></h3>
</div>

app/views/groups/show.html.erb
<% content_for :title do %>
  Informações / <%= @group.name%>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h4>Grupo</h4>
      </div>
      <div class="panel-body">
        <p>
          <strong>Nome:</strong>
          <%= @group.name %>
        </p>

        <p>
          <strong>Endereço:</strong>
          <%= @group.address %>
        </p>

        <p>
          <strong>Cidade:</strong>
          <%= @group.city %>
        </p>            
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h4>Participantes</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-offset-3 col-md-6">  
            <% if @group.user == current_user && !@group.raffled %>
              <%= link_to 'Convidar amigo', '#new_participant_modal', 'data-toggle' => 'modal', class: "btn btn-info btn-block btn-lg" %>
            <% end %> 
          </div>
        </div>
        <br>
        <div id="participants" class="row">
          <% @group.participants.each do |partic| %>
            <%= render partial: 'participants/item_participant', locals: {group: @group, participant: partic} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>              

<div class="modal fade" id="new_participant_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Adicionar amigo</h4>
        </div>
          <%# Render the new participant form (passing modal => true to enable remote => true) %>
          <%= render 'participants/form',  modal: true %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmigoX</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
          <div class="navbar-header">
            <% if user_signed_in? %>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
            <% end %>  
              <a class="navbar-brand" href="/">Amigo X</a>
          </div>
          <!-- /.navbar-header -->

          <%= render 'shared/menu' if user_signed_in? %>
        </nav>

        <div id="page-wrapper" class="<%= 'has-sidemenu' if user_signed_in? %>">
          <% if user_signed_in? %>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= yield :title %></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
          <% end %>


          <% flash.each do |name, msg| %>
            <!-- allow for flash elements to be arrays -->
            <% if msg.class == Array %>
              <% msg.each do |message| %>
                <%= content_tag :div, message, :id => "flash_#{name}", class: "alert alert-info" %>
              <% end %>
            <% else %>
              <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-info" %>
            <% end %>
          <% end %>          

          <%= yield %>
        </div>  
    </div> 
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> as <%= message.timestamp %> disse</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/participants/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for [@group, @participant], remote: remote, html: {role: :form, 'data-model' => 'participant'} do |f| %>
  <div class="modal-body">
    <%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="form-group">
      <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail' %>
      <span class="help-block"></span>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit 'Convidar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
  </div>  
<% end %>

app/views/participants/_item_participant.html.erb
<div class="col-lg-4 col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
  	  <div class="row">
	    <div class="col-xs-3">
		  <i class="fa fa-user fa-3x"></i>
        </div>
	    <div class="col-xs-9 text-right">
        <% if participant.user.blank? %>
          <div><strong><%= participant.email%></strong></div>
        <% else %>
          <div><strong><%= participant.user.username %></strong></div>
        <% end %>
	    </div>
	  </div>
    </div>
    <div class="panel-footer">         
      <% if group.user == current_user && participant.user != current_user && !group.raffled %>
        <span class="pull-left">
	        <%= link_to group_participant_path(group, participant), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } do %>
	        <i class="fa fa-times fa-lg text-danger"></i>
	      <% end%>
	    </span>
      <% end %>  
      <span class="pull-right">
  	    <% if participant.user %>
  		    <strong class="text-primary">Participante Confirmado <i class="fa fa-thumbs-o-up fa-lg"></i></strong>
  	    <% else %>
		      <strong class= "text-danger">Aguardando Confirmação <i class="fa glyphicon-hourglass fa-lg"></i></strong>
  	    <% end %> 
      </span>
      <div class="clearfix"></div> 	  
    </div>
  </div>
</div>

app/views/participants/show.js.erb
$('#participants').append("<%= j render partial: 'item_participant', locals: {group: @group, participant: @participant } %>");
$('#new_participant_modal').modal_success();

app/views/shared/_group_side_menu.html.erb
<li>
    <a href="#"><i class="fa fa-group fa-fw"></i> <%= group_menu.name %><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level">
        <li>
            <%= link_to 'Informações', group_path(group_menu) %>
        </li>
        <li>
            <%= link_to 'Mensagens', messages_group_path(group_menu) %>
        </li>                                
        <li>
            <% if group_menu.raffled? %>
              <%= link_to 'Meu amigo', secret_friend_group_path(group_menu) %>
            <% elsif group_menu.user == current_user %>
              <%= link_to 'Sortear', raffle_group_path(group_menu) %>   
            <% end %>         
        </li>                                
        <li>
            <%= link_to 'Configurações do grupo', edit_group_path(group_menu) if group_menu.user == current_user %>
        </li>
    </ul>
</li>

app/views/shared/_menu.html.erb
<ul class="nav navbar-top-links navbar-right">
  <!-- /.dropdown -->
  <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user fa-fw"></i> <%= current_user.username.split(' ')[0] %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out fa-fw"></i> Logout
            <% end %>
          </li>
      </ul>
      <!-- /.dropdown-user -->
  </li>
  <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
          <li>
              <h4 class="title-menu">Meu Menu</h4>
          </li>
          <li>
            <%= link_to groups_path do %>
              <i class="fa fa-dashboard fa-fw"></i> Início
            <% end %>
          </li>
          <li>
              <h4 class="title-menu">Meus Grupos</h4>
          </li> 
          <%= render partial: "shared/group_side_menu", collection: groups_by_user, as: :group_menu %>
          <li>
              <%= link_to new_group_path do %>
                <i class="fa fa-plus fa-fw"></i> Criar novo grupo
              <% end %>
          </li>
      </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->